### ISSUE TITLE
Crashed when no album title is in URL

### ISSUE THREAD

**Issue by ztgasdf** [R3AP3/amogus#6]
Works: https://music.apple.com/us/album/happier-than-ever/1564530719

Fails: https://music.apple.com/us/album/1564530719

```
  __ _ _ __ ___   ___   __ _ _   _ ___
 / _` | '_ ` _ \ / _ \ / _` | | | / __|
( (_| | | | | | | (_) | (_| | |_| \__ \
 \__,_|_| |_| |_|\___/ \__, |\__,_|___/
repository:             __/ |Ver: 0.3.3
github.com/R3AP3/amogus|___/

Traceback (most recent call last):
  File "C:\Programs\PATH\amogus.py", line 115, in <module>
    main(args.input)
  File "C:\Programs\PATH\amogus.py", line 98, in main
    routine(url_parts[4], url_parts[1])
IndexError: tuple index out of range
```

**Comment by R3AP3** [comment]
This has to do with the routine splitting up the link expecting part 4 of the url to be the ID

Using regular expressions might be more precize here in the future for now use the links with the album cover or the inline search. An update will follow. Thanks for the issue.

**Comment by R3AP3** [comment]
recoded the script, added this parsing function for the url. Should work now i guess.

```python
def url_parse(url):
    # Parse the URL and return the ID, region and type
    split_url = url.split('/')
    if split_url[3] == 'artist' or split_url[3] == 'album':
        return split_url[-1], 'us', split_url[3]
    else:
        return split_url[-1], split_url[3], split_url[4]
```
you could theoretically even leave out the region if you really wanted to
